#!/bin/sh

binfolder=$HOME/.local/bin/

# IFS=$'\n'
rm $binfolder/*-Flatpak

flatpak --columns=app list --app | while read -r app
do
  lastIndx=$(echo "$app" | awk -F. '{ print NF - 1 }')
  lastIndx=$((lastIndx+1))
  printIndx="{print \$$lastIndx}" 
  appname="$(echo "$app" | awk -F  '.' "$printIndx")-Flatpak"
  # applaunchname=$(echo "$app" | awk '{print $2}')
  appdir="$binfolder$appname"
  touch "$appdir"
  echo "#!/bin/sh

flatpak run $app

  " > "$appdir"
  # echo "$appdir"
  # echo "$lastIndx"
  echo "$appname   $app"
  chmod +x "$appdir"
done

