#!/bin/sh

binfolder=$HOME/.local/bin/

flatpak list --app | while read -r app
do
  appname="$(echo "$app" | awk -F '\t' '{print $1}')-Flatpak"
  appname="$(echo "$appname" | sed 's/ /-/g')"
  applaunchname=$(echo "$app" | awk -F '\t' '{print $2}')
  appdir="$binfolder$appname"
  #echo "$applaunchname"
  touch "$appdir"
  echo "#!/bin/sh

flatpak run $applaunchname

  " > "$appdir"
  #echo "$appdir"
  echo "$appname\t$applaunchname\t$appdir"
  chmod +x "$appdir"
done

